### ISSUE TITLE
Tool not showing

### ISSUE THREAD

**Issue by regiszanandrea** [Eolica-Web/nova-locale-switcher#1]
Hi,
I was testing your package but I couldn't make it work.

I followed your steps but nothing is showed.

Here is my configuration:
- laravel 8
- nova 3.12.0
- php 7.4
- ubuntu 20.04

Can you take a look on this?

**Comment by dllobell** [comment]
Hello @regiszanandrea, thanks for posting your issue!

First of all, I warn you that for a number of reasons we have changed our name from "tramuntana-studio" to "eolica", so I suggest that you modify your dependency within your composer file since the old one will be deleted definitively in the future.

Regarding your problem, we forgot to document one of the steps, quite important one... :), you must include the `locale-switcher` Vue component inside Nova's layout blade file. I just updated the Readme accordingly explaning how to do it.

Tell me if you can make it work now.

Thank you very much !

**Comment by regiszanandrea** [comment]
Thanks @dllobell, I suspected that one step was missing. I gonna test later.

**Comment by Broutard** [comment]
You also should to copy the nova `layout.blade.php`... only partials are copied with `php artisan nova:publish`
